### ISSUE TITLE
NameError: undefined local variable or method `filter` for <Temporal::Client:0x000000010bca6f00>>

### ISSUE THREAD

**Issue by rhashim02-tc** [coinbase/temporal-ruby#249]
In the [Temporal client code](https://github.com/coinbase/temporal-ruby/blob/41a8e923e52f62a6727e3ce6ffa2d68090b29439/lib/temporal/client.rb#LL408C5-L410C8), the `query_workflow_executions` method uses a local variable named filter within the method body but does not accept it as a parameter, causing a `NameError` to be raised. 

The full error message is the following:
```
"error":"#<NameError: undefined local variable or method `filter' for #<Temporal::Client:0x000000010bca6f00>>"
```

This method was introduced in #177.

**Comment by rhashim02-tc** [comment]
See PR here for a quick fix -> https://github.com/coinbase/temporal-ruby/pull/250
